---
- hosts: extensa
  become: yes
  vars_files:
  - ../files/vars.yml
  tasks:
    - name: add port
      lineinfile:
        path: "{{ sshdconfig }}" 
        regexp: "^Port 22" 
        line: "Port 2233"
        insertafter: "^Port 22" 
        state: present

    - name: restart sshd
      service:
        name: sshd
        state: restarted

        #    - name: ansible plugin zshrc
        #      become_user: wolle
        #      become_method: sudo
        #      blockinfile:
        #        path: /home/wolle/.zshrc
        #        marker: "^plugins="
        #        block: |
        #           ansible
        #        insertafter: "^plugins="
        #        state: present

    - name: docker run alias
      become_user: wolle
      become_method: sudo
      lineinfile:
        path: /home/wolle/.zshrc
        line: alias dra="sudo docker run ansible:1.6"
        insertafter: EOF
