AWSTemplateFormatVersion: "2010-09-09"
Description: "Ec2 with Ubuntu for Dev Work"

Parameters:
  TeamName:
    Type: String
    Description: Capability Stream within BCBSA
    Default: CDE
  VPCID:
    Type: String
    Description: VPC to deploy J2 Resources into
    Default: vpc-0d209c90c9c090588

Resources: 
  MyEC2Instance: 
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-0305d0b03812a425e"
      #UserData: "base-64EncodedUserdata="
      KeyName: !Ref SSHPemKey
      #IamInstanceProfile: "ec2-instance-IAM-Role"
      InstanceType: "t1.micro"
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          DeleteOnTermination: true
          SubnetId: !Ref DevSubnet
          GroupSet: 
            - !Ref DevSecGroup
      BlockDeviceMappings: 
        - DeviceName: "/dev/sdb"
          Ebs: 
            VolumeType: "io1"
            Iops: "200"
            DeleteOnTermination: "false"
            VolumeSize: "50"

  SSHPemKey:
    Type: AWS::EC2::KeyPair
    Properties: 
      KeyName: DevEc2KeyMartin
      PublicKeyMaterial: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpp6KdrXO4HqnQQsPbYGgB8XTNzFnCkKkzf44VO2nkwVhoXJm1cntauE9S2BBAVdZ4/+KFrAQ/II6/zK0XQf3TA5fZvP0KY4zcHjgjDjV6uY43IIWk3zEwSUg9WFbMDjUCNIjj2qNeULfL6Z7r0AMPY5FJ7nFwO2woQlEz0UMLiH+qPlMPIi8tDphLnmtyQ2NVobasc/m8nvIjNx68IgyYUaKsMYD7sSVWXc0sOh08ctSIKSJBxnvMp9Kt0XsXFnjxRUDH3IL3hVJgvnSDEK6AyVwUpVem/mo+772zTwa2vUIdVhN2DGEz15wOrb4xNG8UD1QS+YGE1GLVE3QiEqoj CogAWS"

  DevVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'

  DevSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DevVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-east-1a"

  DevSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref DevVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 44
          ToPort: 80
          CidrIp: 0.0.0.0/0
  # myDNS:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId:  Z98yxxxx
  #     Name: www.DNS-Name.com
  #     Type: A
  #     TTL : '300'
  #     ResourceRecords: 
  #     - Fn::GetAtt: [ MyEC2Instance, PublicIp ]
