AWSTemplateFormatVersion: "2010-09-09"
Description: "Creating a User through Cloudformation"
Resources:
  IAMTest1:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "terraform"
      Policies: 
       - PolicyName: "ansibleAccess"
         PolicyDocument:
           Version: "2012-10-17"
           Statement:
             - Effect: "Allow"
               Action: "*"
               Resource: "*"
  IAccess:
    Type: "AWS::IAM::AccessKey"
    Properties:
      UserName: !Ref "IAMTest1"
Outputs:
  AccesKey:
    Value: !Ref "IAccess"
  SecretKey:
    Value: !GetAtt [ "IAccess", "SecretAccessKey" ]
